### PR TITLE
Handle running the game under Windows

### PR DESCRIPTION
**Pull request by c3er**
I just watched the [Video on  8-Bit Show And Tell](https://youtu.be/VG0ODzV48fI) that mentions your project at the end.

As I tried to run the game under Windows, it failed because of missing Curses library. I added a "requirements-win.txt" (assuming that Curses runs out of the box on Unix-like operating systems) and extended the README with a description for installing the requirement.

### CODE REVIEW

**Comment by Chgowiz** [comment]
Hi c3er! Thanks!

I'm such a github newbie, I have no idea what to do with your contributions? Do you know? What does the things you've added do?

I'm more familiar with TFS and Visual Studio like version control system, if that helps.

**Comment by c3er** [comment]
Well, i suggest following steps:

1. Open a command line in your project directory and enter `git remote add c3er https://github.com/c3er/PyDungeon.git`  
   This adds my fork to your list of remote repositories. "c3er" will be the reference name to the new remote repository. You may choose any other name.
1. Enter `git fetch c3er`  
   This copies my changes to your repository without changing anything on your actual files yet
1.  Enter `git checkout requirements-handling`  
   You switch the branch and your files should change accordingly to my changes
1. Check whether all still works as expected and whether you like my changes. If not, put your complains here🙂
1. In either case, enter `git checkout master`  
   Restores the state of before
1. If you like my changes, enter `git merge requirements-handling`  
   This integrates my commit to your master branch
1. Enter `git push origin master`
  To publish

If you have any local changes, that you don't want to commit yet, perform following steps before and after all the steps above:
- Before: `git stash -u`  
   Backup the local changes, including untracked (i.e. not yet added) files
- After: `git stash pop`  
   Restores your "backup".

Hope, this will work out.

By the way, because you seem to work under Windows and in the case you don't know it yet: There is an awesome GUI for Git, named [GitExtensions](https://github.com/gitextensions/gitextensions/releases). You can do all the actions above via menus and dialogs and it has a nice view of your current repository state.

**Comment by Chgowiz** [comment]
This is all really good info. I use Visual Studio, so I will try to
replicate what you just laid out.

But... what do your changes do?  The "requirements-win.txt" file -- I'm not
that experienced with Python, is that something I missed doing?

Michael

**Comment by c3er** [comment]
As I said above, I failed first to run the game because of the missing Curses library in Windows.

In the Python world it is common to put the names of external libraries in a file named "requirements.txt". If you enter `pip install -r requirements.txt` the `pip` tool will install all listed libraries in your Python installation, so that they are available to any scripts that want to use them.

Because I assume that the `windows-curses` library is only necessary under Windows, I named the file "requirements-win.txt" instead of "requirements.txt".

Is this understandable so far? I guess, you have the `windows-curses` library already on your system somehow.

BTW, your code does not really show, that you are new to Python. Good work!🙂

**Review by Chgowiz — APPROVED** [review]
Thanks for the help! I'm including these into the master.

**Pull request merged**
